-- MySQL Script generated by MySQL Workbench
-- Mon Jun  4 10:41:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema work_angel_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `work_angel_db` DEFAULT CHARACTER SET utf8 ;
USE `work_angel_db` ;

-- -----------------------------------------------------
-- Table `work_angel_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_angel_db`.`user` (
  `user_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Lastname` VARCHAR(45) NULL,
  `Forename` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `SALT` VARCHAR(45) NULL,
  `userPicture` BLOB(32000000) NULL,
  PRIMARY KEY (`user_ID`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `work_angel_db`.`employer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_angel_db`.`employer` (
  `employer_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `SALT` VARCHAR(45) NULL,
  `employerPicture` BLOB(32000000) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`employer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `work_angel_db`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_angel_db`.`skill` (
  `skill_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`skill_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `work_angel_db`.`user_has_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_angel_db`.`user_has_skill` (
  `user_user_ID` INT(11) NOT NULL,
  `skill_skill_ID` INT NOT NULL,
  `Level` INT(1) NULL,
  PRIMARY KEY (`user_user_ID`, `skill_skill_ID`),
  INDEX `fk_user_has_skills_skills1_idx` (`skill_skill_ID` ASC),
  INDEX `fk_user_has_skills_user_idx` (`user_user_ID` ASC),
  CONSTRAINT `fk_user_has_skills_user`
    FOREIGN KEY (`user_user_ID`)
    REFERENCES `work_angel_db`.`user` (`user_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_skills_skills1`
    FOREIGN KEY (`skill_skill_ID`)
    REFERENCES `work_angel_db`.`skill` (`skill_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `work_angel_db`.`matches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_angel_db`.`matches` (
  `employer_employer_ID` INT NOT NULL,
  `user_user_ID` INT(11) NOT NULL,
  `Compability` INT NULL,
  `user_accepted` BIT NULL,
  `employer_accepted` BIT NULL,
  PRIMARY KEY (`employer_employer_ID`, `user_user_ID`),
  INDEX `fk_employer_has_user_user1_idx` (`user_user_ID` ASC),
  INDEX `fk_employer_has_user_employer1_idx` (`employer_employer_ID` ASC),
  CONSTRAINT `fk_employer_has_user_employer1`
    FOREIGN KEY (`employer_employer_ID`)
    REFERENCES `work_angel_db`.`employer` (`employer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employer_has_user_user1`
    FOREIGN KEY (`user_user_ID`)
    REFERENCES `work_angel_db`.`user` (`user_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `work_angel_db`.`employer_needs_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work_angel_db`.`employer_needs_skill` (
  `employer_employer_ID` INT NOT NULL,
  `skill_skill_ID` INT NOT NULL,
  PRIMARY KEY (`employer_employer_ID`, `skill_skill_ID`),
  INDEX `fk_employer_has_skills_skills1_idx` (`skill_skill_ID` ASC),
  INDEX `fk_employer_has_skills_employer1_idx` (`employer_employer_ID` ASC),
  CONSTRAINT `fk_employer_has_skills_employer1`
    FOREIGN KEY (`employer_employer_ID`)
    REFERENCES `work_angel_db`.`employer` (`employer_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employer_has_skills_skills1`
    FOREIGN KEY (`skill_skill_ID`)
    REFERENCES `work_angel_db`.`skill` (`skill_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
